name: nasa_immersive_od
description: A showcase project all developed by myself
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  mocktail: ^1.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true